apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotable
  template:
    metadata:
      labels:
        app: quotable
    spec:
      containers:
        - name: quotable
          image: app-image
          ports:
            - containerPort: 3000
