apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
namespace: default
commonLabels:
  app: quotable-local
images:
  - name: app-image
    newName: quotable-local
    newTag: latest
