apiVersion: v1
kind: Service
metadata:
  name: kubernetes-github-example-quotable
spec:
  selector:
    app: kubernetes-github-example-quotable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
