on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  deployments: write
  statuses: write
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_INLINE_CACHE: 1
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        env:
          REQUEST_BODY: |
            ${{ format('{{
              "ref": "{0}",
              "transient_environment": false,
              "production_environment": true,
              "auto_merge": false,
              "environment": "production",
              "required_contexts": ["test"]
            }}', github.ref) }}
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          data: ${{ toJson(env.REQUEST_BODY) }}
      - name: set deployment status to in progress
        id: start_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: in_progress
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v2
        with:
          sha: ${{ github.sha }}
      - name: configure AWS credentials
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: ${{ secrets.AWS_SESSION_DURATION }}
      - uses: ./.github/workflows/actions/ecr-push
        id: ecr-push
        with:
          ecr-repo-name: ${{ secrets.ECR_REPO }}
          build-target: app
          image-tag: production
          sha: ${{ github.sha }}
      - id: deploy-to-kubernetes
        uses: ./.github/workflows/actions/kube-deploy
        with:
          aws-eks-cluster: ${{ secrets.AWS_EKS_CLUSTER }}
          app-name: ${{ secrets.APP }}
          ecr-repo-name: ${{ secrets.ECR_REPO }}
          image-ref: ${{ steps.ecr-push.outputs.image-ref }}
      - name: set deployment status to success
        id: successful_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment_url: ${{ format('http://{0}', steps.deploy-to-kubernetes.outputs.url) }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: success
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: set deployment status to failure
        id: failed_deployment
        uses: octokit/request-action@v2.x
        if: failure()
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: failure
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
