name: main-deployment
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run functional tests
        run: npm run container-test-functional
      - name: run e2e tests
        run: npm run container-test-e2e
  push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/ecr-push
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-role-duration-seconds: ${{ secrets.AWS_SESSION_DURATION }}
          ecr-repo-name: ${{ secrets.ECR_REPO }}
          build-target: app
  kubernetes:
    needs: [push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/kubernetes
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-role-duration-seconds: ${{ secrets.AWS_SESSION_DURATION }}
          aws-eks-cluster: ${{ secrets.AWS_EKS_CLUSTER }}
          app-name: ${{ secrets.APP }}
          ecr-repo-name: ${{ secrets.ECR_REPO }}
