name: main-deployment
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  APP: quotable
  ECR_REPO: kubernetes-github-example/quotable

jobs:
  deploy:
    uses: postman-solutions-eng/kubernetes-github-example/.github/workflows/deploy.yaml@main
    with:
      app-name: quotable
      ecr-repo-name: kubernetes-github-example/quotable
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AWS_SESSION_DURATION: ${{ secrets.AWS_SESSION_DURATION }}
      AWS_EKS_CLUSTER: ${{ secrets.AWS_EKS_CLUSTER }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
