name: pr-deployment
on:
  issue_comment:
    types: [created]
permissions:
  id-token: write
  contents: read
  deployments: write
  statuses: write
  pull-requests: write
jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - name: check if commenter has permission to deploy
        id: check_permissions
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/collaborators/:sender/permission
          repository: ${{ github.repository }}
          sender: ${{ github.event.sender.login }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: acknowledge deployment request to commenter
        id: check
        if: |
          fromJson(steps.check_permissions.outputs.data).permission ==  'admin' || fromJson(steps.check_permissions.outputs.data).permission == 'write'
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: check if commenter has permission to deploy
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
  setup-deployment:
    runs-on: ubuntu-latest
    needs: [deploy-check]
    outputs:
      deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
    if: needs.deploy-check.outputs.triggered == 'true'
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
          environment: ${{ format('dev-pr-{0}', github.event.issue.number) }}
          transient_environment: true
          auto_merge: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: set deployment status to in progress
        id: start_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: in_progress
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  push:
    name: build and push image to ECR
    needs: [setup-deployment]
    runs-on: ubuntu-latest
    outputs:
      deployment: ${{ needs.setup-deployment.outputs.deployment }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/ecr-push
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-role-duration-seconds: ${{ secrets.AWS_SESSION_DURATION }}
          ecr-repo-name: ${{ secrets.ECR_REPO }}
          build-target: app
          image-tag: ${{ format('dev-pr-{0}', github.event.issue.number) }}
  kubernetes:
    name: deploy to Kubernetes
    needs: [push]
    runs-on: ubuntu-latest
    outputs:
      deployment: ${{ needs.push.outputs.deployment }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/kubernetes
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-role-duration-seconds: ${{ secrets.AWS_SESSION_DURATION }}
          aws-eks-cluster: ${{ secrets.AWS_EKS_CLUSTER }}
          ecr-repo-name: ${{ secrets.ECR_REPO }}
          app-name: ${{ format('{0}-dev-pr-{1}', secrets.APP, github.event.issue.number) }}
          image-tag: ${{ format('dev-pr-{0}', github.event.issue.number) }}
  set-deployment-outcome:
    needs: [kubernetes]
    runs-on: ubuntu-latest
    steps:
      - name: set deployment status to success
        id: successful_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ needs.kubernetes.outputs.deployment }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: success
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: set deployment status to failure
        id: failed_deployment
        uses: octokit/request-action@v2.x
        if: failure()
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ needs.kubernetes.outputs.deployment }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: failure
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
