name: test
on:
  push:
    branches-ignore: [main]
  pull_request:
  workflow_dispatch:
env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run functional tests
        shell: bash
        run: make test
