name: pr-test
on:
  push:
    branches-ignore: [main]
  pull_request:
env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
permissions:
  id-token: write
  contents: read
jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run functional tests
        run: npm run container-test-functional
      - name: run e2e tests
        run: npm run container-test-e2e
